### PR TITLE
Replace web3-react with wagmi and add seif, tailwind and compass wallet connectors

### LINKED ISSUE #492: Connect wallet flow enhancements
- [ ] Remove connect error messages

When the user selects WalletConnect or Coinbase wallet option and then closes the modal by clicking on "x" or selects Metamask option and then rejects the connection in Metamask:

1. Do not display an error message popup
2. Leave the Connect wallet selection popup open

- [ ] Metamask connect flow 

Web:(Metamask extension is not installed)
When user clicks on the Metamask option  in the Connect wallet popup and he has no Metamask browser extension installed, he will be redirected to  https://metamask.io/ in a new tab (with focus on it)

Web:(Metamask extension installed)
See the "Remove connect error messages" section

Mobile:
When the user clicks on the Metamask connect wallet option on mobile(regardless if he has Metamask mobile app installed or not),he will be redirected to the following page in a new tab (with focus on it)
https://support.metamask.io/hc/en-us/articles/6356387482523-How-to-use-the-MetaMask-Mobile-Browser

### LINKED ISSUE #545: Add support for Trust Wallet
trust wallet currently works and can be used in the app.
however, it is not ideal.

web:
currently, we only support trust wallet via wallet connect. 
please follow this to integrate direct integration to trust wallet
https://developer.trustwallet.com/trust-wallet-browser-extension/extension-guide

mobile:
currently, we allow connecting when clicking the 'metamask' icon. this is working but incorrect implementation.
we should aim to identify the user wallet directly (when using the wallet native browser on mobile).
please follow this to improve the integration
https://github.com/trustwallet/web3-react-trust-wallet

### LINKED ISSUE #1203: Compass wallet - add support for compass wallet
https://github.com/sei-protocol/sei-js

### LINKED ISSUE #1208: Cannot test coinbase wallet locally
Coinbase wallet is failing locally as the CoinbaseWalletSDK uses process.env and it is undefined when running in dev mode. Goal is to be able to use the coinbase wallet locally the same way as metamask.

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
fix #1203 
fix #545 
fix #492 
fix #1208
close #1220 (@solana/web3.js no longer needed)

## Done
- Replace web3-react by wagmi
- Improve wallet connect error handling according to [EIP-1993](https://eips.ethereum.org/EIPS/eip-1193) and add back button on error to try connecting again
- Hide gnosis safe if not in iframe, as it only connected with iframe
- Move GTM and getConnector functionality to the wagmi library. Available GTM events for all wallets:
  - Auto-connection and auto-disconnection (through the wallet interface)
  - Manual connection and manual disconnection
  - Account change
- Update tanstack-query from v4 to v5 ([migration guide](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5)) and keep the same behaviour
  - Replace isLoading with isPending ([docs](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5#status-loading-has-been-changed-to-status-pending-and-isloading-has-been-changed-to-ispending-and-isinitialloading-has-now-been-renamed-to-isloading))
  - Replace cachetime with gcTime ([docs](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5#rename-cachetime-to-gctime))
  - Change mutation and query input to object ([docs](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5#supports-a-single-signature-one-object))
  - Remove onError callbacks that were outputting errors to console.error. Instead output errors via QueryCache if there is an error and query.meta.errorMessage is defined. Same error output as before is shown ([docs](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5#callbacks-on-usequery-and-queryobserver-have-been-removed))
- Add placeholder wallets
  - Add Seif Wallet
  - Add Tailwind Wallet
  - Add Compass Wallet
- Add detection for injected EIP-6963 providers
  - If expected default providers are not detected show a placeholder for them in the list and display "Wallet not installed" error on connect.
  - If an expected default provider is detected, then remove their placeholder and instead show the injected provider
  - If an injected provider that is not part of the default list is detected, add them to the list as well to let the user choose them
- Tenderly on Sei now supported with tenderly faucet config moved to network config
- Coinbase Wallet improvements
  - Wallet now works locally
  - When it is not installed, user is prompted to use the extension-free [smart wallet](https://www.coinbase.com/en-gb/wallet/smart-wallet) option
- Metamask wallet: when it is not installed, the user is shown a modal with a link to download the desktop or mobile version
- 'build-essential' package was not in the playground docker used in the e2e workflow so it is now installed before dependencies are. It's required as `make` and other C/C++ libraries were not available and were required.

## Note
- All wallets apart from Seif work locally. Seif only injects its provider on safe environments, so please always use the preview link to test it.

### CODE REVIEW

File: src/libs/web3/web3.connectors.ts [hunk 1]
```diff
@@ -52,9 +59,18 @@ export const networkConnection: Connection = {
 // INJECTED CONNECTOR
 // ********************************** //
 
-const [web3Injected, web3InjectedHooks] = initializeConnector<MetaMask>(
-  (actions) => new MetaMask({ actions, onError })
-);
+const [web3Injected, web3InjectedHooks] = getInjectedProvider('ethereum')
+  ? initializeConnector<MetaMask>(
```
Comment (zavelevsky) [inline src/libs/web3/web3.connectors.ts:63]: not a fan of ternary operators for a non-trivial logic but if it's too annoying to initialize otherwise then ok

File: src/libs/web3/web3.connectors.ts [hunk 2]
```diff
@@ -136,3 +152,84 @@ export const coinbaseWalletConnection: Connection = {
...
+  type: 'tailwindWallet',
+  name: 'Tailwind Wallet',
+  logoUrl: iconTailwindWallet,
+};
+
+// ********************************** //
+// Compass WALLET CONNECTOR
+// ********************************** //
+
+export const [web3CompassWallet, web3CompassWalletHooks] = getInjectedProvider(
```
Comment (zavelevsky) [inline src/libs/web3/web3.connectors.ts:177]: I don't get it - are we initializing the connectors in any case?

File: src/libs/web3/web3.utils.ts [hunk 3]
```diff
@@ -16,6 +19,28 @@ const { type } = parser.getDevice();
...
+/**
+ * Get the injected wallet provider in window
+ * Returns window.ethereum if window.ethereum exists, window.ethereum[flag], is true and window.ethereum is not metamask
+ * Otherwise, returns window[walletObject]
+ *
+ * @param flag name of the flag in window.ethereum to check. If undefined, will not check this flag and default to walletObject
+ * @param walletObject name of the object in window that the injected provider will populate
+ * @returns Injected provider in wallet or undefined if not present
+ */
+export function getInjectedProvider(walletObject: string, flag?: string) {
```
Comment (zavelevsky) [inline src/libs/web3/web3.utils.ts:31]: This method is a bit messy in the sense that it both gets info from the caller but also makes some attempts on the ethereum object. I'd simply go with each of the current callers using their own logic to get the injected provider. If you separate the connectors into their own modules or classes, each with its implementation then it becomes more tidy and clear and can be used in a generic way. Since most do a similar things you can offer a method that's initialized with the expected object name.

This method here is also implicitly dictating who wins. If there's ethereum and no flag it's alway ethereum.

**Review by zavelevsky — CHANGES_REQUESTED** [review]

File: src/libs/web3/noconnector.ts [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+  public constructor(name: string) {
+    super(`${name} not installed, redirecting to website...`);
+    this.name = NoConnectorError.name;
+    Object.setPrototypeOf(this, NoConnectorError.prototype);
+  }
+}
+
+export class NoConnector extends Connector {
+  /** {@inheritdoc Connector.provider} */
+  public declare readonly provider: undefined;
```
Comment (GrandSchtroumpf) [inline src/libs/web3/noconnector.ts:19]: I'm surprise you need to declare it. Can you explain why ?

File: src/libs/web3/noconnector.ts [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+  actions: Actions;
+  name: string;
+  url: string;
+}
+
+export class NoConnectorError extends Error {
+  public constructor(name: string) {
+    super(`${name} not installed, redirecting to website...`);
+    this.name = NoConnectorError.name;
+    Object.setPrototypeOf(this, NoConnectorError.prototype);
```
Comment (GrandSchtroumpf) [inline src/libs/web3/noconnector.ts:13]: This is the first time I see this kind of implementation. It seems a little hacky.

File: src/libs/web3/web3.connectors.ts (hunk 2 above)
Comment (GrandSchtroumpf) [reply src/libs/web3/web3.connectors.ts:177]: As Doron says, I would recommend exporting a factory function and use it only when you need it. This would reduce CPU usage a launch time.

**Comment by ashachaf** [comment]
- [ ] compass wallet connection issue
flow:
- make sure your compass wallet is locked
- visit sei.carbondefi.xyz
- click to connect compass wallet
- you would see the unlock screen of compass wallet
- following unlocking, you see the app pending screen
actual:
you would need to close the wallet connect popup on the app and try again for the flow to work
expected:
following the unlock, to force the connect popup to show up on the compass wallet

- [ ] compass wallet connection flow
flow:
- click to connect compass wallet
- see the connect popup on the wallet
- reject connection
actual: wallet connect popup on the app still waiting for response
expected: app identify the user action and indicate in the app. (either by closing the wallet connect popup or displaying an error)

- [ ] trying to connect metamask
image
image

- [ ] trying to connect tailwind
image
image

File: src/libs/web3/web3.utils.ts (hunk 3 above)
Comment (tiagofilipenunes) [reply src/libs/web3/web3.utils.ts]: This method follows the methodology used by Rainbow where the window.ethereum object is the default as specified in [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193).

Agree with separating the EIP1193 connectors' injected provider retrieval logic though, will do that for the wagmi integration

File: src/libs/web3/noconnector.ts (hunk 4 above)
Comment (tiagofilipenunes) [reply src/libs/web3/noconnector.ts]: This was leftover from porting code from web3-react. Resolved

File: src/libs/web3/noconnector.ts (hunk 5 above)
Comment (tiagofilipenunes) [reply src/libs/web3/noconnector.ts]: Same as above

**Comment by Costa769** [comment]
- [ ] No Tailwind wallet option displayed
There is no Tailwind wallet option in the wallet select menu, tried different devices and Chrome/Brave browsers. Tried a few projects on the SEI ecosystem and there is no Tailwind option there too, might be a wallet issue

- [ ] Seif open wallet issue
While I was able to connect the wallet by selecting Seif option, clicking on Seif extension icon show me the following error after several minutes of loading
image

- [ ] Compass wallet connect issue

**How to reproduce**

1. Lock compass wallet
2. Select Compass wallet from the connect wallet list on the SEI app
3. Enter password and unlock wallet in the compass wallet window

**Expected:**
 Compass wallet will prompt the user to connect to SEI app
 **Actual:**
 After unlocking the wallet window is closed without prompting the user to connect to SEI app
 Connect wallet menu remains open 
image

Seen this behavior on other websites on SEI ecosystem, so might be a wallet issue again

**Comment by ashachaf** [comment]
- [ ] user reject the connect wallet transaction on the wallet interface
current:
image
image
image
image


image
image
image

updated:
- identify use reject action
- update the text to this: Connection rejected. Please approve dApp connection on your wallet.
- add CTA: "back to wallet connect" or "back" which will close the error popup and reopen the wallet selection popup.

- [ ] main app should not show the sei wallet option
when visiting app.carbondefi.xyz, the new sei related wallet should not be visible.

- [ ] wallet not installed
current:
image

updated:
add a "back to wallet connect" or "back" option which will open the wallet selection popup.

File: src/libs/wagmi/wagmi.constants.ts [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+const CHAIN_RPC_HEADERS = tenderlyRpc ? {} : config.network.rpc.headers || {};
+const CHAIN_ID = config.network.chainId;
+
+if (typeof CHAIN_RPC_URL === 'undefined') {
+  throw new Error(`rpcUrl must be defined in config folder`);
+}
+
+export const IS_TENDERLY_FORK = !!tenderlyRpc;
+
+export enum EnumConnectionType {
```
Comment (GrandSchtroumpf) [inline src/libs/wagmi/wagmi.constants.ts:15]: Is it used ? 
Prefer string literals over enum : 
```ts
type ConnectionType = 'METAMASK' | 'COINBASE_WALLET' | ...
```
Or :
```ts
const connectionTypes = ['METAMASK', ...] as const;
export type ConnectionTypes = typeof connectionTypes[number];
```

File: src/libs/wagmi/wagmi.constants.ts [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+  METAMASK,
+  COINBASE_WALLET,
+  WALLET_CONNECT,
+  GNOSIS_SAFE,
+}
+
+export enum SupportedChainId {
+  MAINNET = CHAIN_ID,
+}
```
Comment (GrandSchtroumpf) [inline src/libs/wagmi/wagmi.constants.ts:24]: Use a regular object instead 
```suggestion
export enum SupportedChainId {
  MAINNET = CHAIN_ID,
}
```
```suggestion
export const SupportedChainId = {
  mainnet: CHAIN_ID,
}
```

**Comment by ashachaf** [comment]
- [ ] connecting coinbase wallet cause tailwind to open 
Uploading Screen Recording 2024-06-13 at 18.42.45.mov…

File: src/config/sei/common.ts [hunk 8]
```diff
@@ -72,4 +83,28 @@ export const commonConfig: AppConfig = {
       parser: tokenListParser('pacific-1'),
     },
   ],
+  tenderly: {
```
[the remark this answers is not in the document]
Comment (tiagofilipenunes) [reply src/config/sei/common.ts:86]: So that the tenderly faucet and e2e tests can work on Sei too

File: src/libs/wagmi/config.ts [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+import { configChains, configTransports } from './chains';
+
+export const wagmiConfig = createConfig({
+  chains: configChains,
+  syncConnectedChain: true,
+  connectors: configConnectors,
+  transports: configTransports,
+});
+
+declare module 'wagmi' {
```
[the remark this answers is not in the document]
Comment (tiagofilipenunes) [reply src/libs/wagmi/config.ts:12]: To improve type inference: https://wagmi.sh/react/typescript#config-types

File: src/libs/wagmi/connectors.ts [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+  name: string;
+  icon?: string;
+}) => {
+  return createConnector(() => {
+    return {
+      id: id,
+      name: name,
+      type: id + PLACEHOLDER_TAG,
+      icon: icon,
+      async setup() {},
```
[the remark this answers is not in the document]
Comment (tiagofilipenunes) [reply src/libs/wagmi/connectors.ts:40]: To match the `createConnector` expected `createConnectorFn` argument type https://github.com/wevm/wagmi/blob/e2377a302c40c2d8504cdfd2f20afbb5f343aef5/packages/core/src/connectors/createConnector.ts#L25

File: src/libs/wagmi/connectors.ts [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+const isIframe = () =>
+  typeof window !== 'undefined' && window?.parent !== window;
+
+const getConfigConnectors = (): CreateConnectorFn[] => {
+  const store = createStore();
+
+  const providersToHide = store
+    .getProviders()
+    .map((provider) => provider.info.name.toLowerCase());
+  if (!isIframe()) providersToHide.push('safe');
```
[the remark this answers is not in the document]
Comment (tiagofilipenunes) [reply src/libs/wagmi/connectors.ts:122]: The isIframe uses the same checks that the gnosis connector performs at https://github.com/wevm/wagmi/blob/e2377a302c40c2d8504cdfd2f20afbb5f343aef5/packages/connectors/src/safe.ts#L87

There is another check that we're in a safe wallet that happens via the allowedDomains param in https://github.com/bancorprotocol/carbon-app/blob/36bac6b4ea664e2be16c9e5130937378a08e9231/src/libs/wagmi/connectors.ts#L108

I'll add a comment

File: src/libs/wagmi/connectors.ts [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+      onChainChanged() {},
+      async onDisconnect(_error) {},
+      async getProvider() {},
+    };
+  });
+};
+
+const getDefaultConnector = (connectorType: SelectableConnectionType) => {
+  switch (connectorType) {
+    case 'Compass Wallet':
```
[the remark this answers is not in the document]
Comment (tiagofilipenunes) [reply src/libs/wagmi/connectors.ts:64]: The issue is that the rdns which should be the unique id is not the same between the injected EIP-6963 and the default connector. So we instead just see if any injected EIP-6963 shares the same name as the default connectors and if so, hide the default ones. I think this makes sense as you don't want to get your wallet confused with another with the same name.

**Comment by tiagofilipenunes** [comment]
> * [ ]  connecting coinbase wallet cause tailwind to open
>       Uploading Screen Recording 2024-06-13 at 18.42.45.mov…

Flagged with them.

**Review by ashachaf — APPROVED** [review]

File: src/libs/wagmi/connectors.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (tiagofilipenunes) [reply src/libs/wagmi/connectors.ts:66]: Using rdns ids which are unique to the wallet - they're different between the wagmi connectors and the EIP-6963 injected ones.

File: src/components/common/WalletIcon.tsx [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+  icon,
+  className,
+}: Props) => {
+  if (isImposter) {
+    return <IconImposterLogo className={className} />;
+  }
+
+  // For EIP6963 injected wallets
+  if (icon) {
+    return <img alt="Wallet Logo" src={icon} className={className} />;
```
Comment (GrandSchtroumpf) [inline src/components/common/WalletIcon.tsx:29]: Set it to `loading="lazy"` to prevent eager load.
Also maybe alt should be "Injected Wallet"

File: src/libs/wagmi/useWagmiImposter.ts [hunk 14]
```diff
@@ -0,0 +1,26 @@
+import { useCallback, useState } from 'react';
+import { lsService } from 'services/localeStorage';
+
+export const useWagmiImposter = () => {
+  const [imposterAccount, setImposterAccount] = useState<string>(
+    lsService.getItem('imposterAccount') || ''
+  );
+
+  const handleImposterAccount = useCallback(
```
Comment (GrandSchtroumpf) [inline src/libs/wagmi/useWagmiImposter.ts:9]: Personally I would have use a `useEffect` for that.

**Review by GrandSchtroumpf — APPROVED** [review]

**Comment by ashachaf** [comment]
- [ ] (optional) compass wallet doesnt trigger the connect dapp popup
flow:
- click to connect compass wallet
- see the "unlock" wallet popup and confirm it
expected:
see the connect dapp popup to conenct wallet
actual:
no wallet connect popup, and the app shows the loading animation waiting for user interaction on the wallet popup.
