### PR TITLE
Parse network symbol from config

### LINKED ISSUE #1413: [SENTRY] [BUG] Network symbol must be 2-6 characters when adding new network
When adding a new network, the network symbol must be 2-6 characters otherwise it will fail and the user won't be able to connect.

How to replicate:
- Remove Celo Network from MetaMask
- Try to connect wallet to celo.carbondefi.xyz

Expected: Success
Current: Fail, with error indicating that the network symbol must be between 2-6 characters.

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
fix #1413 

- Remove parenthesis and content within
- Limit the length of the symbol

### CODE REVIEW

File: src/libs/wagmi/chains.ts [hunk 1]
```diff
@@ -3,12 +3,19 @@ import config from 'config';
 import { CHAIN_ID, RPC_HEADERS, RPC_URLS } from './wagmi.constants';
 import { http } from 'wagmi';
 
+// Native Currency Symbol
+// Remove content in parenthesis
+// Symbol must be 2-6 characters to add new network
+const nativeCurrencySymbol = config.network.gasToken.symbol
```
Comment (GrandSchtroumpf) [inline src/libs/wagmi/chains.ts:9]: Add a `@todo(#xxxx)` comment associated with an issue to refactor this.

**Review by GrandSchtroumpf — APPROVED** [review]
