### PR TITLE
Fix inconsistent back button styling

### LINKED ISSUE #1186: Inconsistent back button styling
Throughout the app, the arrow component to go back shows an inconsistent behaviour/styling.

Different behaviour observed:
1. [Individual strategy activity](https://app.carbondefi.xyz/strategy/340282366920938463463374607431768212114?actions=create%2Cdeposit)
  - Hover on button, text next to button not clickable. Back button has different styling
2. [Strategy Creation](https://app.carbondefi.xyz/strategies/create)
  - No hover effect, text next to button not clickable
3. [Simulate](https://app.carbondefi.xyz/simulate/result?baseToken=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&quoteToken=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&buyMin=%222423.8241758241762%22&buyMax=%222726.8021978021982%22&buyBudget=%221000%22&buyIsRange=true&sellMin=%223332.7582417582422%22&sellMax=%223635.7362637362642%22&sellBudget=%221%22&sellIsRange=true&start=%221681858800%22&end=%221713394799%22&type=recurring)
  - No hover effect, text next to button is clickable

Suggestion: Change them all to match the activity page back button's look and feel.

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
Fix #1186

Make back button styling consistent.

Current: 'bg-background-800' for most buttons, and 'bg-background-900 hover:bg-background-800' in the strategy page

Change to: 'bg-background-900 hover:bg-background-800' as the strategy page is the most recent page made.

Make "Simulate Strategy" in the Simulator Results page not clickable.

### CODE REVIEW

**Review by Costa769 — APPROVED** [review]

File: src/components/common/BackButton.tsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import { ReactComponent as IconChevronLeft } from 'assets/icons/chevron-left.svg';
+import { cn } from 'utils/helpers';
+
+interface Props {
+  onClick?: () => void;
+  className?: string;
+}
+
+export const BackButton = ({ onClick, className }: Props) => {
```
Comment (GrandSchtroumpf) [inline src/components/common/BackButton.tsx:9]: I would recommend to split it into two component : 
- `BackButton`: with `history.back()` 
- `BackLink`: with a specific `to`

File: src/components/common/BackButton.tsx [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  return (
+    <button
```
Comment (GrandSchtroumpf) [inline src/components/common/BackButton.tsx:11]: add the `type="button"` to prevent it to submit if in a `form`

File: src/pages/simulator/result/index.tsx [hunk 3]
```diff
@@ -34,49 +34,47 @@ export const SimulatorResultPage = () => {
...
+              buyMax: ctx.search.buyMax,
+              buyBudget: ctx.search.buyBudget,
+              sellMin: ctx.search.sellMin,
+              sellMax: ctx.search.sellMax,
+              sellBudget: ctx.search.sellBudget,
+              buyIsRange: ctx.search.buyIsRange,
+              sellIsRange: ctx.search.sellIsRange,
+            }}
+          >
+            <BackButton className="mr-16" />
```
Comment (GrandSchtroumpf) [inline src/pages/simulator/result/index.tsx:55]: We should never put a button inside a link. They are focusable element so it leads to double Tab action. Also interactive element are not permitted as descendant of an anchor : 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#technical_summary

File: src/pages/simulator/result/index.tsx [hunk 4]
```diff
@@ -34,49 +34,47 @@ export const SimulatorResultPage = () => {
...
+              baseToken: ctx.search.baseToken,
+              quoteToken: ctx.search.quoteToken,
+              start: ctx.search.start,
+              end: ctx.search.end,
+              buyMin: ctx.search.buyMin,
+              sellMax: ctx.search.sellMax,
+              spread: ctx.search.spread,
+            }}
+          >
+            <BackButton className="mr-16" />
```
Comment (GrandSchtroumpf) [inline src/pages/simulator/result/index.tsx:74]: same here

File: src/components/common/BackButton.tsx (hunk 2 above)
Comment (tiagofilipenunes) [reply src/components/common/BackButton.tsx]: done

**Review by zavelevsky — APPROVED** [review]
