### PR TITLE
Trade Page - bis

### LINKED ISSUE #737: Trade page - depth and order incorrect display
in order to show the data on the trade page, we rely on min/max values of the buy/sell orders.

sometimes, leftover dust, provide incorrect data points that prevent from displaying the data correctly.

pair: BNT/USDC
fork: https://dashboard.tenderly.co/bancor/carbon-test-forks/fork/003e732c-0339-49f0-968f-1cc941095fcc
if you check this you would notice that there is a strategy with very attractive buy BNT price yet when you try to use it, the rate is different from the min rate indication as a result of token decimal precision. 

suggested improvement:
try to identify the actual rate for the minimum amount of liquidity.
instead of fetching min price, try to run the match function with 1 wei (and repeat with 10x amount) until you get a valid response. this response would be used as the min value point.

### LINKED ISSUE #1384: [Trade Page] Layout & URL
Ref #1167

The trade page have two sections : 
- Form
- Explorer

image

The `Form` section will be using subpages, while the 
They will both share the same URL and search params, so they should not collide.

## Common
- path: `/trade/$type/$explorer`
- search params: 
```ts
interface BaseTradeSearch {
  base: string;
  quote: string;
  historyStart?: number;
  historyEnd?: number;
}
```

### Strategy Type
- path: `/trade/tradeType/$explorer`
- search params: 
```ts
interface TradeTypeSearch {
  type: 'disposable' | 'recurring' | 'overlapping' | 'spot';
}
```

### Disposable
- path: `/trade/disposable/$explorer`
- search params: 
```ts
interface TradeDisposableSearch {
  direction: StrategyDirection;
  settings: StrategySettings;
  min?: string;
  max?: string;
  budget?: string;
}
```

### Recurring
- path: `/trade/recurring/$explorer`
- search params: 
```ts
interface TradeRecurringSearch {
  buyMin?: string;
  buyMax?: string;
  buyBudget?: string;
  buySettings: StrategySettings;
  sellMin?: string;
  sellMax?: string;
  sellBudget?: string;
  sellSettings: StrategySettings;
}
```

### Overlapping
- path: `/trade/overlapping/$explorer`
- search params: 
```ts
interface TradeOverlappingSearch {
  marketPrice?: string;
  min?: string;
  max?: string;
  spread?: string;
  anchor?: 'buy' | 'sell';
  budget?: string;
  chartType?: 'history' | 'range';
}
```

### Spot
- path: `/trade/spot/$explorer`
- search params: 
```ts
interface TradeSpotSearch {
  direction: StrategyDirection;
  amount?: number;
  anchor?: StrategyDirection; // direction=buy&anchor=buy -> receive
}
```

### Overview
- path: `/trade/$type/overview`
- search params: 
```ts
interface TradeOverviewSearch {
  direction: StrategyDirection;
  amount?: number;
  anchor?: StrategyDirection; // direction=buy&anchor=buy -> receive
}
```

### Portfolio
- path: `/trade/$type/portfolio`
- search params: 
```ts
interface TradePortfolioSearch {
  tokenId?: string;
}
```

### Activity
- path: `/trade/$type/activity`
- search params: 
```ts
interface TradeActivitySearch {
  limit?: number;
  offset?: number;
  ids?: string[];
  actions?: ActivityAction[];
  start?: Date;
  end?: Date;
}
```

## Routes
```ts
interface TradeRouteSearch {
  '/trade/tradeType/overview': BaseTradeSearch & TradeTypeSearch & TradeOverviewSearch;
  '/trade/tradeType/portfolio': BaseTradeSearch & TradeTypeSearch & TradePortfolioSearch;
  '/trade/tradeType/activity': BaseTradeSearch & TradeTypeSearch & TradeActivtySearch;
  '/trade/disposable/overview': BaseTradeSearch & TradeDisposableSearch & TradeOverviewSearch;
  '/trade/disposable/portfolio': BaseTradeSearch & TradeDisposableSearch & TradePortfolioSearch;
  '/trade/disposable/activity': BaseTradeSearch & TradeDisposableSearch & TradeActivtySearch;
  '/trade/recurring/overview': BaseTradeSearch & TradeRecurringSearch & TradeOverviewSearch;
  '/trade/recurring/portfolio': BaseTradeSearch & TradeRecurringSearch & TradePortfolioSearch;
  '/trade/recurring/activity': BaseTradeSearch & TradeRecurringSearch & TradeActivtySearch;
  '/trade/overlapping/overview': BaseTradeSearch & TradeOverlappingSearch & TradeOverviewSearch;
  '/trade/overlapping/portfolio': BaseTradeSearch & TradeOverlappingSearch & TradePortfolioSearch;
  '/trade/overlapping/activity': BaseTradeSearch & TradeOverlappingSearch & TradeActivtySearch;
  '/trade/spot/overview': BaseTradeSearch & TradeSpotSearch & TradeOverviewSearch;
  '/trade/spot/portfolio': BaseTradeSearch & TradeSpotSearch & TradePortfolioSearch;
  '/trade/spot/activity': BaseTradeSearch & TradeSpotSearch & TradeActivtySearch;
}
```

### LINKED ISSUE #1385: [Trade Page] Token Selection
Ref  #1167
image

Change current token selection: select on token at a time. Each button should open the token list modal
image

### LINKED ISSUE #1386: [Trade Page] Forms
ref #1167

## Type
image
Reuse the `CreateStrategyOption` component.
Change Icons

## Disposable
image
Default direction is "sell"

## Recurring
**Search validation** : buy is specify but not sell, ignore buy information

Create a stepper : 
1. Sell section: if no sell price ([mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16108-86510&t=gsoBgx1Bku815OUE-0))
2. Buy section: if sell price but no buy budget ([mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16108-85839&t=gsoBgx1Bku815OUE-0))
3. Summary: if sell price, buy price & buy budget ([mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16108-93480&t=gsoBgx1Bku815OUE-0))

## Overlapping
**Search validation**: if anchor should be disable (price beyond market), remove budget & anchor

Create a stepper : 
1. Price section: if no budget ([mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16128-36730&t=gsoBgx1Bku815OUE-0))
2. Budget section: ([mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16108-88905&t=gsoBgx1Bku815OUE-0))
3. Summary ([mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16108-94786&t=gsoBgx1Bku815OUE-0))

## Market
Default to direction sell
[mockup](https://www.figma.com/design/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?node-id=16108-91956&t=gsoBgx1Bku815OUE-0)

### LINKED ISSUE #1387: [Trade Page] Duplicate & create link
ref #1167
Every "create strategy" link should return to `/trade`

Duplicate should redirect to the summary page

### PR DESCRIPTION
**Pull request by GrandSchtroumpf**
fix #1384
fix #1385
fix #1386
fix #1387

closes #737

### CODE REVIEW

**Comment by Costa769** [comment]
-[ ] Swap between tokens resets to default strategy type
When user clicks on the arrow icon and swaps between base and quote tokens, the strategy selection resets to default
image

**Comment by Costa769** [comment]
- [ ] Remove the border from gear icon
On Spot trade page, remove the border around the gear icon, see example below
image

- [ ] Change checkbox text
Update checkbox text on concentrated strategy page
Current: "I've reviewed the warning(s) but choose to proceed."
New: "I've approve the token deposit(s) and distribution"

- [ ] Update "Notice" text on the spot strategy page
Current:
image
Updated:
image

**Comment by Costa769** [comment]
### Optional

- [ ] Add strategy type to the create strategy CTA
For all strategy types except spot, add strategy type indication to the create strategy CTA
**Strategy type -> Text to show on the CTA**
Recurring strategy type -> show "Create Recurring Strategy" 
Concentrated strategy type-> show "Create Concentrated Strategy" 
Limit/Range strategy type
- **IF** user selected limit-> show "Create Limit Strategy" 
- **ELSE,IF** user selected range-> show "Create Range Strategy"

Example(recurring):
image

**Comment by Costa769** [comment]
- [ ] Change Spot Sell/Buy form titles
Current: 
image
Update:
Sell tab-> Change "Sell High ETH" to "Sell ETH for USDC"
Buy tab-> Change "Buy Low ETH" to "Buy ETH with USDC"

- [ ] Add rebase and fee tokens warning in the token selection section
image

- [ ] Add token pair tooltip
Add the same token pair tooltip that we currently show on the first step of the strategycreation flow
image

- [ ] Add "Buy or Sell" and "With" indicators to the token selection fields
image

- [ ] Add Buy low and Sell high tooltips for limit/range and recurring strategies
Those are the same tooltips currently implemented, example:
image

- [ ] Add "i" icons woth tooltips for strategy types
The tooltip will be shown when mouse hover over the "i" icon inside the strategy option, similar behavior to the one on the simulate page
image

File: src/libs/routing/routes/trade.ts [hunk 1]
```diff
@@ -1,20 +1,145 @@
...
+  max?: string;
+  budget?: string;
+}
+
+// TRADE RECURRING
+export interface TradeRecurringSearch extends TradeSearch {
+  buyMin?: string;
+  buyMax?: string;
+  buyBudget?: string;
+  buySettings: StrategySettings;
```
Comment (tiagofilipenunes) [inline src/libs/routing/routes/trade.ts:36]: Can be optional as the default is `limit`

File: src/libs/routing/routes/trade.ts [hunk 2]
```diff
@@ -1,20 +1,145 @@
...
+  sellMin?: string;
+  sellMax?: string;
+  sellBudget?: string;
```
Comment (tiagofilipenunes) [inline src/libs/routing/routes/trade.ts:39]: Can be optional as the default is `limit`

**Review by tiagofilipenunes — CHANGES_REQUESTED** [review]
Great work on the update of the trade page!

Notes:
- Can you make the Strategy Type tooltip icons 12x12px size and the hover outline-background-400 in the Strategy Type options and the select token buttons to match the simulator form?
- Shouldn't e2e screenshots change here?
- In the Trading Strategy component, for narrow screens, the concentrated icon disappears. Example at 416px.
image

- Old url subpath like 
```
/strategies/create/recurring?base=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&quote=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
```
Are not redirected right now to 

```
/trade/recurring?base=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&quote=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
```

**Comment by Costa769** [comment]
- [ ] Update "No liquidity available" warning text
When Spot option is selected and there is no liquidity available for the selected pair, we show the following message:
image

Update the text to:

"Looks like there isn't sufficient liquidity to execute your trade, but don’t worry, here's a pro tip: 
Set your own price with a limit/range order and the built-in solver system will search chain-wide liquidity to help efficiently fill you order, all while you enjoy MEV sandwich attack resistance, zero slippage, and zero fees!"

- [ ] Mobile view is broken
Maybe we can remove the token and strategy icons on mobile
image

File: src/components/activity/ActivitySection.tsx [hunk 3]
```diff
@@ -1,67 +1,52 @@
...
+  const { activities, status } = useActivity();
+  const { location } = useRouterState();
   const { aboveBreakpoint } = useBreakpoints();
+  if (status === 'pending') {
+    return (
+      <div className="grid place-items-center md:min-h-[600px]">
+        <CarbonLogoLoading className="h-[80px]" />
+      </div>
+    );
+  }
```
[the remark this answers is not in the document]
Comment (GrandSchtroumpf) [reply src/components/activity/ActivitySection.tsx:38]: Not really because it uses `activityQuery` not `activityMetaQuery`.

File: src/components/strategies/common/NoStrategies.tsx [hunk 4]
```diff
@@ -0,0 +1,12 @@
+import { NotFound } from 'components/common/NotFound';
+
+export const NoStrategies = () => {
```
Comment (tiagofilipenunes) [inline src/components/strategies/common/NoStrategies.tsx:3]: This component is not used anymore

File: e2e/pages/trade.spec.ts [hunk 5]
```diff
@@ -40,16 +39,16 @@ const testCases: TradeTestCase[] = [
...
         targetValue: '10.004863',
       },
-      {
-        sourceValue: '10',
-        targetValue: '10.004838',
-      },
+      // {
+      //   sourceValue: '10',
+      //   targetValue: '10.004838',
+      // },
```
Comment (tiagofilipenunes) [inline e2e/pages/trade.spec.ts:45]: I'm okay with reducing the number of trades here. Can you remove the comment?

**Review by tiagofilipenunes — APPROVED** [review]
LGTM, just minor comments

1. In the trade page, on the spot tab, I'm seeing these search params:

`&source=&target=`
